name: Backend Deploy to EC2

on:
  push:
    branches:
      - main
    #paths:
      #- 'myfoodmap-back/**' # (중요) 백엔드 폴더 이름이 backend라면! 아니면 이 줄 지워.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # S3에 배포 파일 압축해서 업로드하기
      - name: Upload to S3
        run: |
          aws deploy push \
            --application-name mzc-ksw-myfoodmap-backend-app \
            --description "This is a revision for the application" \
            --ignore-hidden-files \
            --s3-location s3://mzc-ksw-myfoodmap-backend-651914029420/myfoodmap---back.zip \
            --source .

      # CodeDeploy에게 "배포해!"라고 명령하기
      - name: Create CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name mzc-ksw-myfoodmap-backend-app \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name mzc-ksw-myfoodmap-backend-group \
            --s3-location bucket=mzc-ksw-myfoodmap-backend-651914029420,key=myfoodmap---back.zip,bundleType=zip